###################################################
## @section BigBang Integration
## Big Bang params for domain, istio, network, monitoring, sso.
###################################################
domain: dev.bigbang.mil

routes:
  inbound:
    anchore-api:
      enabled: true
      selector:
        app.kubernetes.io/component: api
      gateways:
        - istio-gateway/public-ingressgateway
      hosts:
        - anchore-api.{{ .Values.domain }}
      http:
        # Disable ability to hit metrics on virtual service
        - match:
            - uri:
                prefix: /metrics
          route:
            - destination:
                host: anchore-enterprise-anchore-enterprise-api.anchore.svc.cluster.local
                port:
                  number: 8228
          fault:
            abort:
              percentage:
                value: 100
              httpStatus: 403
        # Default route for everything else
        - match:
            - uri:
                prefix: /
          route:
            - destination:
                host: anchore-enterprise-anchore-enterprise-api.anchore.svc.cluster.local
                port:
                  number: 8228
    anchore-ui:
      enabled: true
      selector:
        app.kubernetes.io/component: ui
      gateways:
        - istio-gateway/public-ingressgateway
      hosts:
        - anchore.{{ .Values.domain }}
      service: anchore-enterprise-anchore-enterprise-ui.anchore.svc.cluster.local
      port: 3000
  outbound:
    anchore-data-service:
      enabled: true
      hosts:
      - data.anchore-enterprise.com

istio:
  enabled: false

  sidecar:
    enabled: false
    outboundTrafficPolicyMode: "REGISTRY_ONLY"

  serviceEntries:
    custom: []

  authorizationPolicies:
    enabled: false
    custom: []

  # Default peer authentication
  mtls:
    # STRICT = Allow only mutual TLS traffic
    # PERMISSIVE = Allow both plain text and mutual TLS traffic
    mode: STRICT

networkPolicies:
  enabled: false
  ingress:
    to:
      catalog:8082:
        podSelector:
          matchLabels:
            app.kubernetes.io/component: catalog
        from:
          k8s:
            monitoring-monitoring-kube-prometheus@monitoring/prometheus: false
      simplequeue:8083:
        podSelector:
          matchLabels:
            app.kubernetes.io/component: simplequeue
        from:
          k8s:
            monitoring-monitoring-kube-prometheus@monitoring/prometheus: false
      analyzer:8084:
        podSelector:
          matchLabels:
            app.kubernetes.io/component: analyzer
        from:
          k8s:
            monitoring-monitoring-kube-prometheus@monitoring/prometheus: false
      policy:8087:
        podSelector:
          matchLabels:
            app.kubernetes.io/component: policyengine
        from:
          k8s:
            monitoring-monitoring-kube-prometheus@monitoring/prometheus: false
      api:8228:
        podSelector:
          matchLabels:
            app.kubernetes.io/component: api
        from:
          k8s:
            monitoring-monitoring-kube-prometheus@monitoring/prometheus: false
      reports:8558:
        podSelector:
          matchLabels:
            app.kubernetes.io/component: reports
        from:
          k8s:
            monitoring-monitoring-kube-prometheus@monitoring/prometheus: false
      notifications:8668:
        podSelector:
          matchLabels:
            app.kubernetes.io/component: notifications
        from:
          k8s:
            monitoring-monitoring-kube-prometheus@monitoring/prometheus: false
      ui-redis:9121:
        from:
          k8s:
            monitoring-monitoring-kube-prometheus@monitoring/prometheus: false
  egress:
    definitions:
      anchore-data-service:
        to:
          - ipBlock:
              cidr: 0.0.0.0/0
        ports:
          - port: 443
            protocol: TCP
      ldap-subnets:
        to:
          - ipBlock:
              cidr: 192.168.0.0/16
          - ipBlock:
              cidr: 172.16.0.0/12
          - ipBlock:
              cidr: 10.0.0.0/8
        ports:
          - port: 636
            protocol: TCP
      notification-services:
        to:
          - ipBlock:
              cidr: 0.0.0.0/0
      redis-subnets:
        to:
          - ipBlock:
              cidr: 192.168.0.0/16
          - ipBlock:
              cidr: 172.16.0.0/12
          - ipBlock:
              cidr: 10.0.0.0/8
        ports:
          - port: 6379
            protocol: TCP
      registry-subnets:
        to:
          - ipBlock:
              cidr: 0.0.0.0/0
    from:
      "*":
        to:
          k8s:
            tempo/tempo:9411: false
      analyzer:
        podSelector:
          matchLabels:
            app.kubernetes.io/component: analyzer
        to:
          definition:
            registry-subnets: true
      api:
        podSelector:
          matchLabels:
            app.kubernetes.io/component: api
        to:
          definition:
            redis-subnets: false
            notification-services: true
      catalog:
        podSelector:
          matchLabels:
            app.kubernetes.io/component: catalog
        to:
          definition:
            registry-subnets: true
      datasyncer:
        podSelector:
          matchLabels:
            app.kubernetes.io/component: datasyncer
        to:
          definition:
            anchore-data-service: true
      notifications:
        podSelector:
          matchLabels:
            app.kubernetes.io/component: notifications
        to:
          definition:
            notification-services: true
      smoketest:
        podSelector:
          matchLabels:
            app.kubernetes.io/component: smoketest
        to:
          definition:
            registry-subnets: true
      ui:
        podSelector:
          matchLabels:
            app.kubernetes.io/component: ui
        to:
          definition:
            ldap-subnets: true
            redis-subnets: false
  additionalPolicies: []

# Enable/disable Keycloak SSO integration
# If enabled, also enable OAuth - global.oauthEnabled
sso:
  enabled: false
  name: "keycloak"
  acsHttpsPort: -1
  spEntityId: "platform1_a8604cc9-f5e9-4656-802d-d05624370245_bb8-anchore"
  acsUrl: "https://anchore.bigbang.dev/service/sso/auth/keycloak"
  defaultAccount: "user"
  defaultRole: "read-write" # If roleAttribute is passed, defaultRole will be ignored
  roleAttribute: "" # Optional, defines the Keycloak attribute to use to map roles/permissions
  requireSignedAssertions: false
  requireSignedResponse: true
  idpMetadataUrl: "https://login.dso.mil/auth/realms/baby-yoda/protocol/saml/descriptor"
  host: "login.dso.mil"
  realm: "baby-yoda"

  # Configure resource requests and limits in the ./chart/templates/bigbang/sso/configure-sso.yaml job
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi

  containerSecurityContext:
    runAsUser: 1001
    runAsGroup: 1001
    capabilities:
      drop:
        - ALL

# Enable Prometheus Monitoring
monitoring:
  enabled: false
  namespace: monitoring
  serviceMonitor:
    scheme: ""
    tlsConfig: {}

###################################################
## @section Big Bang Tests Values
## Big Bang params for bbtests
###################################################
bbtests:
  enabled: false
  scripts:
    image: registry1.dso.mil/ironbank/anchore/cli/cli:0.9.4
    envs:
      ANCHORE_CLI_URL: "http://{{ include \"enterprise.api.fullname\" . }}:{{ .Values.upstream.api.service.port }}/v2"
      ANCHORE_CLI_USER: admin
      ANCHORE_SCAN_IMAGE: quay.io/prometheus/node-exporter:latest
    secretEnvs:
      - name: ANCHORE_CLI_PASS
        valueFrom:
          secretKeyRef:
            name: "{{ include \"enterprise.fullname\" . }}"
            key: ANCHORE_ADMIN_PASSWORD
  cypress:
    resources:
      requests:
        cpu: "2"
        memory: "4Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
    artifacts: true
    envs:
      cypress_url: "http://{{ include \"enterprise.ui.fullname\" . }}:{{ .Values.upstream.ui.service.port }}"
      cypress_user: admin
      cypress_registry: docker.io
      cypress_repository: anchore/grype
      cypress_tag: latest
    secretEnvs:
      - name: cypress_password
        valueFrom:
          secretKeyRef:
            name: "{{ include \"enterprise.fullname\" . }}"
            key: ANCHORE_ADMIN_PASSWORD

###################################################
## @section Global Resource Parameters
## Global params used by all child charts
###################################################
global:
  fullnameOverride: ""
  nameOverride: "anchore-enterprise"

###################################################
## @section Common Resource Parameters
## Common params used by all Anchore k8s resources
###################################################

# -- Values to pass to [the upstream Anchore Enterprise chart](https://github.com/anchore/anchore-charts/blob/main/stable/enterprise/values.yaml)
# @default -- Upstream chart values
upstream:

  #BB Change to disable upstream redis and use BB redis instead.
  ui-redis:
    chartEnabled: false

  ##BB Disable upstream postgresql and use BB postgresql instead.
  postgresql:
    chartEnabled: false
    externalEndpoint: ""
    auth:
      username: anchore
      password: anchore-postgres,123
      database: anchore
    primary:
      service:
        ports:
          postgresql: 5432

  image: registry1.dso.mil/ironbank/anchore/enterprise/enterprise:5.25.1
  imagePullSecretName: private-registry
  kubectlImage: registry1.dso.mil/ironbank/opensource/kubernetes/kubectl:v1.34
  migrationPodImage: registry1.dso.mil/ironbank/opensource/postgres/postgresql:18.3
  containerSecurityContext:
    capabilities:
      drop:
        - ALL
 
  useExistingLicenseSecret: false
  # Enterprise license: Insert license yaml object below:
  license: {} 

  policyEngine:
    resources:
      limits:
        cpu: 1
        memory: 4G
      requests:
        cpu: 1
        memory: 4G

  ###########################################
  ## @section Anchore Simple Queue Parameters
  ###########################################
  simpleQueue:
    resources:
      limits:
        cpu: 1
        memory: 1G
      requests:
        cpu: 1
        memory: 1G

  ############################################
  ## @section Anchore Notifications Parameters
  ############################################
  notifications:
    resources:
      limits:
        cpu: 1
        memory: 1G
      requests:
        cpu: 1
        memory: 1G

  ######################################################
  ## @section Anchore Analyzer k8s Deployment Parameters
  ######################################################
  analyzer:
    replicaCount: 2
    serviceType: ClusterIP
    resources:
      limits:
        cpu: 1
        memory: 4G
      requests:
        cpu: 1
        memory: 4G

  #####################################################################
  ## @section Anchore Configuration Parameters
  ## Params used for all Anchore Enterprise service configuration files
  #####################################################################

  # Input exclusions in the arrays below:
  anchoreConfig:
    metrics:    
      enabled: true
      auth_disabled: false
    policy_engine:
      vulnerabilities:
        matching:
          exclude:
            providers: []
            package_types: []

  #################################################
  ## @section Anchore API k8s Deployment Parameters
  #################################################
  api:
    service:
      port: 8228
    resources:
      limits:
        cpu: 1
        memory: 4G
      requests:
        cpu: 1
        memory: 4G

  #####################################################
  ## @section Anchore Catalog k8s Deployment Parameters
  #####################################################
  catalog:
    resources:
      limits:
        cpu: 1
        memory: 3G
      requests:
        cpu: 1
        memory: 3G

  #############################################
  ## @section Anchore Reports Worker Parameters
  #############################################
  reportsWorker:
    resources:
      limits:
        cpu: 1
        memory: 1G
      requests:
        cpu: 1
        memory: 1G

  ########################################
  ## @section Anchore Reports Parameters
  ########################################
  reports:
    enabled: true

  #################################
  ## @section Anchore UI Parameters
  #################################
  ui:
    enabled: true
    image: registry1.dso.mil/ironbank/anchore/enterpriseui/enterpriseui:5.25.0
    imagePullSecretName: private-registry
    service:
      port: 3000
    resources:
      limits:
        cpu: 1
        memory: 1G
      requests:
        cpu: 1
        memory: 1G
  ############################################
  ## @section Anchore Upgrade Job Parameters
  ## Upgrade job uses a Helm post-install-hook
  ############################################
  upgradeJob:
    enabled: true
    resources:
      limits:
        cpu: 1
        memory: 1G
      requests:
        cpu: 1
        memory: 1G

#######################################
## @section Anchore UI Redis Parameters
#######################################
# ui-redis is BB version of redis, upstream redis is disabled. 
ui-redis:
  enabled: true
  istio:
    enabled: "{{ .Values.istio.enabled }}"  
  
  ## @param ui-redis.externalEndpoint External Redis endpoint when not using Helm managed chart (eg redis://:<password>@hostname:6379)
  externalEndpoint: ""

  upstream:
    nameOverride: "ui-redis"
    fullnameOverride: "anchore-enterprise-ui-redis"
    auth:
      password: anchore-redis,123
    architecture: standalone
    master:
      persistence:
        enabled: false

    ## ** Big Bang Addition **
    ## @param ui-redis.commonConfiguration Configure common redis parameters
    commonConfiguration: |-
      maxmemory 200mb
      save ""
  cleanUpgrade:
    enabled: false
    redisLabel: "app.kubernetes.io/name: ui-redis"


#######################################
## @section Anchore Database Parameters
#######################################
postgresql:
  enabled: true
  image:
    registry: registry1.dso.mil
    repository: ironbank/opensource/postgres/postgresql
    tag: "18.3"
  global:
    security:
      allowInsecureImages: true
    postgresql:
      auth:
        # -- PostgreSQL User to create
        username: anchore
        # -- PostgreSQL Password for the new user
        password: anchore-postgres,123
        # -- PostgreSQL Database to create
        database: anchore
  primary:
    networkPolicy:
      enabled: false
    persistence:
      mountPath: /var/lib/postgresql
    extraVolumes:
      - name: run-postgresql
        emptyDir: {}
    extraVolumeMounts:
      - name: run-postgresql
        mountPath: /run/postgresql
    resources:
      limits:
        cpu: 1000m
        memory: 4096Mi
      requests:
        cpu: 1000m
        memory: 4096Mi
  metrics:
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 200m
        memory: 256Mi
  postgresqlDataDir: /var/lib/postgresql/pgdata/data
  volumePermissions:
    enabled: false



#######################################
## @section BB Database parameters for templates in ./chart/templates/bigbang/db/
#######################################

# Use Database instance Superuser to create postgresql.postgresDatabase, postgresql.postgresUser, anchore-feeds-db.postgresDatabase, and anchore-feeds-db.postgresUser
postgresqlSuperUser:
  postgresUsername: ""
  postgresPassword: ""
  # Optionally use an existing secret for the superuser credentials with the following defined:
  # PGUSER
  # PGPASSWORD
  # PGDATABASE
  # PGHOST
  # PGPORT
  # ANCHORE_DB
  existingSecret: Null

# Configure resource requests and limits in ./chart/templates/bigbang/db/ensure-anchore-db.yaml and ./chart/templates/bigbang/db/ensure-feeds-db.yaml
ensureDbJobs:
  resources:
    limits:
      cpu: 2
      memory: 2G
    requests:
      cpu: 2
      memory: 2G

