{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "enterprise.fullname" . }}-service-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    prometheus: k8s
    app.kubernetes.io/name: {{ include "enterprise.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "enterprise.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - interval: 30s
      path: /metrics
      params:
        format:
          - prometheus
      port: api
      {{- if .Values.monitoring.serviceMonitor.scheme }}
      scheme: {{ .Values.monitoring.serviceMonitor.scheme }}
      {{- end }}
      {{- if .Values.monitoring.serviceMonitor.tlsConfig }}
      tlsConfig:
{{ toYaml .Values.monitoring.serviceMonitor.tlsConfig | indent 8 }}
      {{- end }}

    - interval: 30s
      path: /metrics
      params:
        format:
          - prometheus
      port: catalog
      {{- if .Values.monitoring.serviceMonitor.scheme }}
      scheme: {{ .Values.monitoring.serviceMonitor.scheme }}
      {{- end }}
      {{- if .Values.monitoring.serviceMonitor.tlsConfig }}
      tlsConfig:
{{ toYaml .Values.monitoring.serviceMonitor.tlsConfig | indent 8 }}
      {{- end }}

    - interval: 30s
      path: /metrics
      params:
        format:
          - prometheus
      port: policyengine
      {{- if .Values.monitoring.serviceMonitor.scheme }}
      scheme: {{ .Values.monitoring.serviceMonitor.scheme }}
      {{- end }}
      {{- if .Values.monitoring.serviceMonitor.tlsConfig }}
      tlsConfig:
{{ toYaml .Values.monitoring.serviceMonitor.tlsConfig | indent 8 }}
      {{- end }}

    - interval: 30s
      path: /metrics
      params:
        format:
          - prometheus
      port: simplequeue
      {{- if .Values.monitoring.serviceMonitor.scheme }}
      scheme: {{ .Values.monitoring.serviceMonitor.scheme }}
      {{- end }}
      {{- if .Values.monitoring.serviceMonitor.tlsConfig }}
      tlsConfig:
{{ toYaml .Values.monitoring.serviceMonitor.tlsConfig | indent 8 }}
      {{- end }}
      #jobLabel: anchore-metrics-simplequeue-api

    {{- if .Values.upstream.feeds.enabled }}
    - interval: 30s
      path: /metrics
      params:
        format:
          - prometheus
      port: feeds-api
      {{- if .Values.monitoring.serviceMonitor.scheme }}
      scheme: {{ .Values.monitoring.serviceMonitor.scheme }}
      {{- end }}
      {{- if .Values.monitoring.serviceMonitor.tlsConfig }}
      tlsConfig:
        {{- toYaml .Values.monitoring.serviceMonitor.tlsConfig | nindent 8 }}
      {{- end }}
      #jobLabel: anchore-metrics-feeds-api
    {{- end }}    

    {{- if .Values.upstream.reports.enabled }}
    - interval: 30s
      path: /metrics
      params:
        format:
          - prometheus
      port: reports
      {{- if .Values.monitoring.serviceMonitor.scheme }}
      scheme: {{ .Values.monitoring.serviceMonitor.scheme }}
      {{- end }}
      {{- if .Values.monitoring.serviceMonitor.tlsConfig }}
      tlsConfig:
{{ toYaml .Values.monitoring.serviceMonitor.tlsConfig | indent 8 }}
      {{- end }}
    {{- end }}

    {{- if .Values.upstream.notifications.enabled }}
    - interval: 30s
      path: /metrics
      params:
        format:
          - prometheus
      port: notifications
      {{- if .Values.monitoring.serviceMonitor.scheme }}
      scheme: {{ .Values.monitoring.serviceMonitor.scheme }}
      {{- end }}
      {{- if .Values.monitoring.serviceMonitor.tlsConfig }}
      tlsConfig:
{{ toYaml .Values.monitoring.serviceMonitor.tlsConfig | indent 8 }}
      {{- end }}
    {{- end }}

    - interval: 30s
      path: /metrics
      params:
        format:
          - prometheus
      port: analyzer
      {{- if .Values.monitoring.serviceMonitor.scheme }}
      scheme: {{ .Values.monitoring.serviceMonitor.scheme }}
      {{- end }}
      {{- if .Values.monitoring.serviceMonitor.tlsConfig }}
      tlsConfig:
{{ toYaml .Values.monitoring.serviceMonitor.tlsConfig | indent 8 }}
      {{- end }}
{{- end }}
